/**
 * Centralized Enums & Types Index
 *
 * All values come from the backend (backend/src/domain/enums.ts) via the
 * @shared/enums path alias. Nothing is defined here — just re-exported for
 * convenience. At runtime, use the useEnums() hook to get live values from /api/enums.
 */

export {
  CURRENCIES,
  ACTIVITY_TYPES,
  TECH_AREA_IDS,
  TECH_AREA_LABELS,
  SOFT_AREA_ID,
  SOFT_SKILL_AREA_LABEL,
  SOFT_SKILL_GROUPS,
  SPECIAL_SUB_AREAS,
  QUESTION_DIFFICULTIES,
  QUESTION_AREAS,
  DEPTH_LABEL_PRESETS,
  SERVICE_CATEGORIES,
  TASK_PRIORITIES,
  TASK_STATUSES,
  SKILL_ITEM_PRIORITIES,
  MATERIAL_TYPES,
  TYPE_LABELS,
  MATERIAL_AREA_IDS,
  MATERIAL_AREA_LABELS,
  MATERIAL_FILTERS,
  TASK_CATEGORIES,
  JOB_STATUSES,
  JOB_PLATFORMS,
  JOB_CATEGORIES,
  OFFER_STATUSES,
  OFFER_PLATFORMS,
  OFFER_CATEGORIES,
  SERVICE_STATUSES,
  SERVICE_PLATFORMS,
  FREELANCE_SERVICE_CATEGORIES,
  CV_FOCUSES,
  CV_LANGUAGE_LEVELS,
  ATS_GRADES,
  AGENT_STATUSES,
  ASSET_KINDS,
  CONNECTOR_TYPES,
  SOCIAL_PLATFORMS,
  MAIL_CHANNELS,
  NOTIFICATION_TYPES,
  ACTIVITY_ACTIONS,
  ACTIVITY_ENTITY_TYPES,
  getAllSoftSkillItems,
  getSoftSkillItemById,
  getSoftSkillCategory,
  isTechArea,
  isSoftSkillArea,
  isMaterialArea,
  isMaterialType,
} from "@shared/enums";

export type {
  Currency,
  ActivityType,
  TechAreaId,
  SoftAreaId,
  QuestionDifficulty,
  QuestionArea,
  ServiceCategory,
  TaskPriority,
  TaskStatus,
  SkillItemPriority,
  SoftSkillItem,
  SoftSkillCategory,
  Material,
  Area,
  AreaGroup,
  MaterialType,
  MaterialAreaId,
  TaskCategory,
  JobStatus,
  JobPlatform,
  JobCategory,
  OfferStatus,
  OfferPlatform,
  OfferCategory,
  ServiceStatus,
  ServicePlatform,
  FreelanceServiceCategory,
  CVFocus,
  CVLanguageLevel,
  ATSGrade,
  AgentStatus,
  AssetKind,
  ConnectorType,
  SocialPlatform,
  MailChannel,
  NotificationType,
  ActivityAction,
  ActivityEntityType,
} from "@shared/enums";
